global:
  scrape_interval: 60s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
