FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy backend package only (and any other python dirs if you add later)
COPY backend ./backend

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "backend.scheduler.cron_job"]

